package org.usfirst.frc1518.CommandBasedTest.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1518.CommandBasedTest.Robot;
import org.usfirst.frc1518.CommandBasedTest.subsystems.DriveTrain;


 
public class Target extends Command {
	public boolean isCompleted = false;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Target() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	/*while(DriveTrain.leftSonic.GetRangeInInches() != DriveTrain.rightSonic.GetRangeInInches()) {
    		if(DriveTrain.leftSonic.GetRangeInInches() < DriveTrain.rightSonic.GetRangeInInches()) {
    			DriveTrain.frontRightDrive.set(0.5);
    			DriveTrain.rearRightDrive.set(0.5);
    			DriveTrain.frontLeftDrive.set(-0.5);
    			DriveTrain.rearLeftDrive.set(-0.5);
    		}
    		else {
    			DriveTrain.frontRightDrive.set(-0.5);
    			DriveTrain.rearRightDrive.set(-0.5);
    			DriveTrain.frontLeftDrive.set(0.5);
    			DriveTrain.rearLeftDrive.set(0.5);
    		}
    		DriveTrain.frontRightDrive.set(0);
			DriveTrain.rearRightDrive.set(0);
			DriveTrain.frontLeftDrive.set(0);
			DriveTrain.rearLeftDrive.set(0);*/
			isCompleted = true;
    	}
    	

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isCompleted;
    }

    // Called once after isFinished returns true
    protected void end() {
    	DriveTrain.frontRightDrive.set(0);
		DriveTrain.rearRightDrive.set(0);
		DriveTrain.frontLeftDrive.set(0);
		DriveTrain.rearLeftDrive.set(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	DriveTrain.frontRightDrive.set(0);
		DriveTrain.rearRightDrive.set(0);
		DriveTrain.frontLeftDrive.set(0);
		DriveTrain.rearLeftDrive.set(0);
    }
}

